# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Technical Resume
author: John C. Gilliland
email: johngilliland@me.com
description: > # this means to ignore newlines until "baseurl:"
  This is my professional resume, highlighting my technical skills.  I have 
  written this as a responsively styled, Jekyll generated website in order to
  gain the ease of maintenance that Jekyll provides.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Resume Settings
resume_avatar:                      "true"
resume_name:                        "John C. Gilliland"
resume_title:                       "Sr. Software Developer"
resume_email:                       "johncgilliland@me.com"
resume_contact:                     "9704 Roxbury Drive, Fishers IN | 502-509-1002 | johncgilliland@me.com"
resume_introduction:                "A full time software developer for the last 17 years.  Extensive experience with Microsoft platforms and technologies, predominantly .NET/C#.  I would enjoy an opportunity that allowed me to continue to improve my skills by learning from those around me, and also include a chance to mentor less experienced developers."
resume_looking_for_work:            "no"

# Resume sections (comment to hide)
resume_section_experience_visible:  true
resume_section_education_visible:   true
resume_section_skills_visible:      true
resume_section_links_visible:       true
resume_section_volunteer_visible:   true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/elusive"
  resume_twitter_url:           "http://twitter.com/johncgilliland"
  resume_linkedin_url:          "https://www.linkedin.com/in/johncgilliland"
  resume_instagram_url:         "https://www.instagram.com/indybushcraft"
  resume_website_url:           "http://johngilliland.net"
resume_print_links:              true